### ISSUE TITLE
Version Error

### ISSUE THREAD

**Issue by SHogenboom** [quarto-ext/typst-templates#4]
@cscheid ; after seeing your posit talk on typst / academic posters I was eager to give it a go - I unfortunately ‘failed’ right after installation. 

I installed the latest pre-release of Quarto (1.4.415) and tried to create the template as described in the readme.

It resulted in the following error:
```
ERROR: The extension Poster is incompatible with this quarto version.

Extension requires: >=99.9.0
Quarto version: 1.4.415

Stack trace:

Extension requires: >=99.9.0
Quarto version: 1.4.415
    at validateExtension (file:///Applications/quarto/bin/quarto.js:42524:15)
    at readExtension (file:///Applications/quarto/bin/quarto.js:42600:5)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async readExtensions (file:///Applications/quarto/bin/quarto.js:42373:35)
    at async readAndCopyExtensions (file:///Applications/quarto/bin/quarto.js:98469:24)
    at async copyExtensions (file:///Applications/quarto/bin/quarto.js:98466:5)
    at async file:///Applications/quarto/bin/quarto.js:105492:17
    at async withSpinner (file:///Applications/quarto/bin/quarto.js:39165:16)
    at async useTemplate (file:///Applications/quarto/bin/quarto.js:105487:9)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:105471:9)
```

The directory was created, but the `quarto-ext` folder has no files.

Any help on how to resolve this is appreciated!

**Comment by cscheid** [comment]
Thanks for the report! The extension is set up to only work on "99.9.9", which is the quarto version you get from github, but we should have (eg) 1.4.415.

**Comment by cscheid** [comment]
This should be fixed by https://github.com/quarto-ext/typst-templates/commit/d914964ddbad48c7c4e158ceb11da383d0ddd7a4.

Just remove that extension folder and reinstall it, and you should be all set.
